### PR TITLE
Manual Code Language Selection

### PR DESCRIPTION
**Pull request by randuhmm**
Adding support for manually selecting the code language. I have had issues with the automatic language detection in highlightjs so this give you the option to explicitly select a language. If you like I can go back and add some test code for this addition. Thanks!

### CODE REVIEW

**Comment by yakky** [comment]
@randuhmm nice addition, thanks. A test is definitely welcome: you can actually extend the current `test_add_plugin` and add the new field to the `data` dictionary and check the markup is updated accordingly.
Also: could you rebase on top of current develop? I fixed to tox configuration to make tests run correctly

**Comment by randuhmm** [comment]
OK, I believe that my branch has been rebased. I don't have any experience with tox, but it seems quite useful to run tests against multiple flavors of Python and third-party libraries. I may add some checks for proper rendering of the template when a language is selected later today. Thanks!

**Comment by yakky** [comment]
@randuhmm apparently there is a misnumbered migration.
`djangocms_highlightjs/migrations/0002_auto_20160608_1749.py` should be `djangocms_highlightjs/migrations/0003_auto_20160608_1749.py` and should depend on `0002_auto_20160409_1853`

**Comment by yakky** [comment]
@randuhmm let me know which kind of help you need to get code in shape for merging

**Comment by randuhmm** [comment]
@yakky Ah I see, I applied the make migrate command before I rebased my develop branch. I can remove the migration and reapply it so that it get numbered properly as 0003.

**Comment by randuhmm** [comment]
@yakky Odd, something else failed with the migrations. Let me take a closer look.

**Comment by randuhmm** [comment]
@yakky - Hmmm it looks like the build is failing on 1.6 because I did not add a south migration. How do you go about adding migrations for south easily? Is the easiest way to create a new django cms project  that depends on 1.6 and install south to be able to run `python manage.py schemamigrate djangocms_highlightjs --auto` ?

**Comment by yakky** [comment]
By running tox -e py27-django16-cms32 you will end up with a proper virtualenv, activate it with `source .tox/py27-djanfo16-cms32` and run `python cms_helper.py makemigrations` without extra parameters, this will generate the south migration

On 10 June 2016 22:05:10 CEST, Jonny notifications@github.com wrote:

> @yakky - Hmmm it looks like the build is failing on 1.6 because I did
> not add a south migration. How do you go about adding migrations for
> south easily? Is the easiest way to create a new django cms project 
> that depends on 1.6 and install south to be able to run `python
> manage.py schemamigrate djangocms_highlightjs --auto` ?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nephila/djangocms-highlightjs/pull/7#issuecomment-225282152

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by randuhmm** [comment]
@yakky - Sorry for making a mess of this PR, haha! I learned some very valuable things with tox, so thanks for helping to walk me through your development process. Cheers!

**Comment by yakky** [comment]
@randuhmm very well done. Thanks for your contribution! Expect a release soon

**Pull request merged**
